[package]
name = "rimu"
version = "0.1.0"
authors = ["Ben Anderson <benanderson@acidic.co.nz>"]
edition = "2018"

[lib]
name = "librimu"
path = "lib/rimu.rs"

[[bin]]
name = "rimu"
path = "src/main.rs"

[dependencies]
nom = "5"
